version: '3.9'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

  prism:
    image: stoplight/prism:3
    container_name: "prism"
    ports:
      - "8003:4010"
    command: mock -h 0.0.0.0 /openapi.yaml
    volumes:
      - ./api/openapi.yaml:/openapi.yaml

  redoc:
    image: 'redocly/redoc'
    container_name: "redoc"
    ports:
      - '8004:80'
    volumes:
      - './api/openapi.yaml:/usr/share/nginx/html/openapi.yaml'
    environment:
      - 'SPEC_URL=openapi.yaml'
